name: Generate documentation
on:
  push:
    branches:
    - UCFSS13
permissions:
  contents: write
jobs:
  generate_documentation:
    if: ( !contains(github.event.head_commit.message, '[ci skip]') )
    runs-on: [self-hosted, Linux, X64]
    concurrency: gen-docs
    steps:
      - name: Generate App Token
        id: app-token-generation
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token-generation.outputs.token }}
      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: ~/SpacemanDMM
          key: ${{ runner.os }}-spacemandmm-${{ secrets.CACHE_PURGE_KEY }}
      - name: Install SpacemanDMM
        run: bash tools/ci/install_spaceman_dmm.sh dmdoc
      - name: Generate documentation
        run: |
          ~/dmdoc
          touch dmdoc/.nojekyll
          echo docs.cm-ss13.com > dmdoc/CNAME
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          clean: true
          token: ${{ steps.app-token-generation.outputs.token }}
          single-commit: true
          folder: dmdoc
